### ISSUE TITLE
feature request: use chat actions instead of status messages

### ISSUE THREAD

**Issue by KnorpelSenf** [SaDi-BRo/openai-bot#1]
Whenever I send a message to the bot, it replies immediately and tells me that I should wait for a reply. Then it edits the message.

It would be much cooler if this status message didn't exist. Instead the bot shows a typing … status. You can do this in grammY with `ctx.replyWithChatAction`. 

For images, the bot could send a status that it's sending a photo. Currently, there's no status message, even though photo replies take even more time.

Amazing bot btw!

**Comment by SaDi-BRo** [comment]
Wow great idea! To be honest I didn't even realize that. I changed them, thanks for your opening this issue :)

**Comment by KnorpelSenf** [comment]
Yay! 🎉
